In [2]:
# IMPORTING THE LIBRARIES
import numpy as np
import pandas as pd

#### 1. How to convert the index of a series into a column of a dataframe?

In [17]:
#Input
mylist = list('chitychitybangbang')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [20]:
#SOLUTION 1
df1 = pd.DataFrame(ser)
df1= pd.DataFrame.transpose(df)

#SOLUTION 2
df2 = pd.DataFrame(ser).transpose()

#### 2. How to get the items of series A not present in series B?

In [30]:
#Input
ser1 = pd.Series([1, 2, 3, 4, 5] )
ser2 = pd.Series([4, 5, 6, 7, 8])

In [37]:
#SOLUTION
pd.concat([ser1,ser2]).drop_duplicates().reset_index(drop = True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

#### 3. How to get frequency counts of unique items of a series?

In [41]:
#Input 
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [43]:
#SOLUTION
ser.value_counts()

b    6
a    5
h    4
c    4
f    4
g    3
e    3
d    1
dtype: int64

#### 4. How to convert a numpy array to a dataframe of given shape?

In [3]:
#Input
ser = pd.Series(np.random.randint(1, 10, 35))

In [11]:
ser_5by7 = np.array(ser).reshape((5,7))
ser_7by5 = np.array(ser).reshape((7,5))

In [16]:
print('5 X 7')
print(ser_5by7)
print('7 x 5')
print(ser_7by5)

5 X 7
[[5 5 3 2 7 6 6]
 [4 2 8 8 5 5 5]
 [2 3 3 1 8 8 9]
 [7 4 3 7 8 9 8]
 [9 1 5 9 7 6 7]]
7 x 5
[[5 5 3 2 7]
 [6 6 4 2 8]
 [8 5 5 5 2]
 [3 3 1 8 8]
 [9 7 4 3 7]
 [8 9 8 9 1]
 [5 9 7 6 7]]


In [13]:
ser_7by5

array([[5, 5, 3, 2, 7],
       [6, 6, 4, 2, 8],
       [8, 5, 5, 5, 2],
       [3, 3, 1, 8, 8],
       [9, 7, 4, 3, 7],
       [8, 9, 8, 9, 1],
       [5, 9, 7, 6, 7]])

#### 5. Calculate the Mean Square Error on a truth and predicted series?

In [25]:
#Input -
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

In [23]:
# Mean Square Error
def mse(y_true, y_pred):
    return np.square(y_true- y_pred).mean()

In [26]:
round(mse(truth, pred), 4)

0.3691

#### 6. CRUD operations on Mongo DB or Postgres using any backend framework(flask or Django)

The respective project was generated in visual studio